name: '✨ Feature/Enhancement Request'
description: 'Suggest a feature or simple enhancement for a blindnet product'
title: '✨ '
labels: ['type: feature']

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which blindnet product(s) are relevant/related to the feature/enhancement request?
      options:
        - Privateform (form.blindnet.io)
        - Dashboard Web Client (dashboard.blindnet.io)
        - DevKit (global)
        - (DevKit) Privacy Computation Engine
        - (DevKit) Data Access Component
        - (DevKit) Storage Connector
        - DevKit - Privacy Components for the Web (global)
        - (PC4W) Privacy Request Capture Interface
        - (PC4W) Data Consumer Interface
        - DevKit - End-to-end encryption SDKs (global)
        - (e2ee) Java Client SDK
        - (e2ee) Java Server SDK
        - (e2ee) .net Framework Server SDK
        - (e2ee) .net Core Server SDK
        - (e2ee) NodeJS SDK
        - (e2ee) JavaScript client SDK
        - (e2ee) PHP SDK
        - Don't known / other
      multiple: true

  - type: dropdown
    id: is-enhancement
    attributes:
      label: Does it seem to be a simple enhancement of an existing feature?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/blindnet-io/openness-framework/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
